### ISSUE TITLE
Contract definition

### ISSUE THREAD

**Issue by stacon** [Spyros-Av/Poker_Hand_Evaluation#1]
@Spyros-Av Before writing any test I need parameters and output from the evaluation function

So please define the following below
Function name,
Function input parameters and types (cards)
Function return type (hand strength and highest card representation)

**Comment by stacon** [comment]
@Spyros-Av , based on the commit above the card type is 
`{ rank: number, suit: 'clubs' | 'diamonds' | 'hearts' | 'spades' }` correct?

the function name is `evaluate` ?

Awaiting fore return type as well

**Comment by Spyros-Av** [comment]
> @Spyros-Av , based on the commit above the card type is
> `{ rank: number, suit: 'clubs' | 'diamonds' | 'hearts' | 'spades' }` correct?
> 
> the function name is `evaluate` ?
> 
> Awaiting fore return type as well

Yes, exactly.
The card type is the object you mentioned.
The evaluation function name is 'evaluate' 
The return type will be an object

**Comment by stacon** [comment]
Is it possible to provide me the structure of the object like I did above with the card object.

**Comment by Spyros-Av** [comment]
The 'evaluate' function returns a 'PlayerHand' type object which is being contructed by its function.
PlayerHand { hand: number, highCard: number }

**Comment by stacon** [comment]
thanks so I will work on the tests based on this input you just gave me!
